#!/usr/bin/env bash
# bump_version.sh — Update all version references from the VERSION file.
#
# Usage:
#   ./tool/scripts/bump_version.sh          # read from VERSION
#   ./tool/scripts/bump_version.sh 1.2.0    # set VERSION and propagate
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
VERSION_FILE="$REPO_ROOT/VERSION"

if [ $# -ge 1 ]; then
  echo "$1" > "$VERSION_FILE"
fi

VERSION="$(tr -d '[:space:]' < "$VERSION_FILE")"

if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "error: invalid version '$VERSION' — expected semver (e.g., 1.0.0)" >&2
  exit 1
fi

echo "Bumping to $VERSION"

# patch_cargo VERSION FILE — update only the [package] or [workspace.package] version,
# not dependency version fields. Targets line 3 for standalone crates,
# or uses awk for the workspace file.
patch_cargo() {
  local ver="$1" file="$2"
  # Use awk to only replace version inside [package] or [workspace.package] sections
  awk -v ver="$ver" '
    /^\[(workspace\.)?package\]/ { in_pkg = 1 }
    /^\[/ && !/^\[(workspace\.)?package\]/ { in_pkg = 0 }
    in_pkg && /^version = "/ { $0 = "version = \"" ver "\""; in_pkg = 0 }
    { print }
  ' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
}

# Rust workspace
patch_cargo "$VERSION" "$REPO_ROOT/tool/Cargo.toml"

# pixl-wasm (excluded from workspace)
patch_cargo "$VERSION" "$REPO_ROOT/tool/crates/pixl-wasm/Cargo.toml"

# Flutter studio (preserves +build suffix)
sed -i '' "s/^version: .*/version: $VERSION+1/" \
  "$REPO_ROOT/studio/pubspec.yaml"

# Aseprite plugin
sed -i '' "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" \
  "$REPO_ROOT/plugins/aseprite/package.json"

# WASM package.json (generated by wasm-pack, but keep in sync)
for pkg in "$REPO_ROOT"/tool/crates/pixl-wasm/pkg/package.json \
           "$REPO_ROOT"/playground/pkg/package.json; do
  [ -f "$pkg" ] && sed -i '' "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" "$pkg"
done

# Regenerate Cargo.lock
(cd "$REPO_ROOT/tool" && cargo generate-lockfile 2>/dev/null) || true

echo "Done. Updated:"
echo "  VERSION                         → $VERSION"
echo "  tool/Cargo.toml                 → $VERSION"
echo "  tool/crates/pixl-wasm/Cargo.toml → $VERSION"
echo "  studio/pubspec.yaml             → $VERSION+1"
echo "  plugins/aseprite/package.json   → $VERSION"
echo ""
echo "Hardcoded .rs strings use env!(\"CARGO_PKG_VERSION\") — no update needed."
